// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ6HOQF1xjaSoDFdiuqx4d0w08tuvK_pM',
    appId: '1:923219245305:web:fb8a1b7ac314bfd4fa4a28',
    messagingSenderId: '923219245305',
    projectId: 'nexter-e6dc4',
    authDomain: 'nexter-e6dc4.firebaseapp.com',
    storageBucket: 'nexter-e6dc4.appspot.com',
    measurementId: 'G-HENDJJPVE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdTTc4fAPoYmLXCwNU0e_DRN_hojliQqw',
    appId: '1:923219245305:android:d5c4534994445d4cfa4a28',
    messagingSenderId: '923219245305',
    projectId: 'nexter-e6dc4',
    storageBucket: 'nexter-e6dc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeFjCsWga14_oT8o6WJhLRoPJFrMwNfHU',
    appId: '1:923219245305:ios:d625a96e15a3ff0efa4a28',
    messagingSenderId: '923219245305',
    projectId: 'nexter-e6dc4',
    storageBucket: 'nexter-e6dc4.appspot.com',
    iosBundleId: 'com.example.nexter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeFjCsWga14_oT8o6WJhLRoPJFrMwNfHU',
    appId: '1:923219245305:ios:9e53a9de79d354a9fa4a28',
    messagingSenderId: '923219245305',
    projectId: 'nexter-e6dc4',
    storageBucket: 'nexter-e6dc4.appspot.com',
    iosBundleId: 'com.example.nexter.RunnerTests',
  );
}
